address = ':3000'
storage = './storage'
interval = 1
logLevel = 'debug'
log = './log'

[host.blog]
from = 'blog.localhost:3000'
to = 'static://blog'

[host.gh]
from = 'gh.localhost:3000'
to = 'https://github.com'

[static.blog]
repo = 'https://github.com/simba-fs/simba-fs'
branch = 'master'
